spring:
  datasource:
    url: jdbc:mysql://mysql:3306/nabootweb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: mysql

authserver:
  url: http://localhost:9000

cors:
  front-app-url: http://app:80