spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nabootweb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
#    password: mysql

authserver:
  url: http://localhost:9000

appserver:
  url: http://localhost:9528

socketserver:
  url: http://localhost:9010

staticserver:
  url: http://localhost:81
  root-path: C:/wamp64/www