server:
  port: 8080

spring:
  profiles:
    active: @spring.active@
  jpa:
    database: mysql
#    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB

springdoc:
  swagger-ui:
    path=/swagger-ui.html