spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nabootweb
    username: root
    password: root

authserver:
  url: http://localhost:9000

appserver:
  url: http://localhost:9528

socketserver:
  enabled: false
  url: http://localhost:9010

staticserver:
  enabled: false
  url: http://localhost:81
  root-path: C:/wamp64/www